# Generated by Django 2.1.1 on 2018-11-02 08:00

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0061_auto_20181101_0746'),
        ('students', '0030_auto_20181101_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassToTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('stu_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.StuClass', verbose_name='班级')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='科目名称')),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='身份')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128, verbose_name='老师姓')),
                ('first_name', models.CharField(max_length=128, verbose_name='老师名')),
                ('gender', models.IntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='老师生日')),
                ('telephone', models.CharField(blank=True, max_length=32, null=True, verbose_name='电话号码')),
                ('wechat', models.CharField(blank=True, max_length=32, null=True, verbose_name='微信')),
                ('course', models.ManyToManyField(blank=True, null=True, to='teacher.Course', verbose_name='老师所带科目')),
                ('identity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Identity', verbose_name='老师的身份')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='老师所在学校')),
                ('wechat_open_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_open_id', to='students.WechatOpenID', verbose_name='openID')),
            ],
        ),
        migrations.AddField(
            model_name='classtoteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, to='teacher.TeacherInfo', verbose_name='老师'),
        ),
    ]
