# Generated by Django 2.1.1 on 2018-11-05 02:44

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20181105_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtoteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, related_name='teacher', to='teacher.TeacherInfo', verbose_name='老师'),
        ),
    ]
