# Generated by Django 2.1.1 on 2018-12-18 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_auto_20181210_0732'),
        ('teacher', '0007_auto_20181113_0232'),
    ]

    operations = [
    ]
