# Generated by Django 2.1.1 on 2019-01-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_auto_20190116_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='wechat',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='微信'),
        ),
    ]
