# Generated by Django 2.1.1 on 2019-02-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0039_auto_20190117_0606'),
        ('teacher', '0024_auto_20190128_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyVisitRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='访问时间')),
                ('reason', models.TextField(max_length=150, verbose_name='访问原因')),
                ('relate_parents', models.ManyToManyField(to='students.StudentParents', verbose_name='关联家长')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentInfo', verbose_name='对应学生')),
            ],
        ),
    ]
