# Generated by Django 2.1.1 on 2019-02-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0026_auto_20190214_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyvisitrecord',
            name='relate_parents',
        ),
        migrations.RemoveField(
            model_name='familyvisitrecord',
            name='student',
        ),
        migrations.DeleteModel(
            name='FamilyVisitRecord',
        ),
    ]
