# Generated by Django 2.1.1 on 2019-03-20 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0029_teacherinfo_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='所在学校'),
        ),
    ]
