# Generated by Django 2.1.1 on 2019-04-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0030_auto_20190320_0610'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classtoteacher',
            table='ClassToTeacher',
        ),
        migrations.AlterModelTable(
            name='identity',
            table='Identity',
        ),
        migrations.AlterModelTable(
            name='teacherinfo',
            table='TeacherInfo',
        ),
    ]
