# Generated by Django 2.1.1 on 2018-10-11 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='过敏源')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=32, verbose_name='国籍')),
                ('english_name', models.CharField(max_length=32, verbose_name='english')),
                ('images', models.FileField(upload_to='country_img')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_condition', models.IntegerField(choices=[(1, '一居室'), (2, '二居室'), (3, '三居室'), (4, '三居以上')], default=1, verbose_name='居住条件')),
                ('living_type', models.IntegerField(choices=[(1, '一居室'), (2, '二居室'), (3, '三居室'), (4, '三居以上')], null=True, verbose_name='居住类型')),
                ('language', models.IntegerField(choices=[(1, '中文普通话'), (2, '中文方言'), (3, '听力语言'), (4, '英语'), (5, '其他外语')], default=1, verbose_name='家庭语言')),
                ('create_time', models.DateField(auto_now=True, verbose_name='创建日期')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relations', models.CharField(max_length=16, verbose_name='家庭关系')),
                ('Is_living', models.BooleanField(verbose_name='是否共同居住')),
                ('handle_shuttle', models.BooleanField(verbose_name='是否为主要接送人')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '再婚'), (2, '离异'), (3, '留守'), (4, '领养'), (5, '单亲'), (6, '其他')], verbose_name='家庭状况')),
            ],
        ),
        migrations.CreateModel(
            name='GraduateInstitutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='学校名称')),
            ],
        ),
        migrations.CreateModel(
            name='HealthInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(null=True, verbose_name='身高')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='体重')),
                ('vision_left', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='左眼视力')),
                ('vision_right', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='右眼视力')),
                ('vision_status', models.IntegerField(null=True, verbose_name='视力情况')),
                ('disability', models.IntegerField(choices=[(1, '无'), (2, '视力'), (3, '听力语言'), (4, '智力'), (5, '肢体'), (6, '精神')], default=1, verbose_name='残疾')),
                ('record_date', models.DateField(auto_now=True, verbose_name='记录日期')),
                ('blood_type', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'O'), (4, 'AB'), (5, '不知道')], verbose_name='血型')),
            ],
        ),
        migrations.CreateModel(
            name='HomeAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=16, verbose_name='省')),
                ('city', models.CharField(max_length=16, verbose_name='市')),
                ('region', models.CharField(max_length=16, verbose_name='区县')),
                ('address', models.CharField(max_length=128, verbose_name='详细地址')),
                ('record_time', models.DateField(auto_now=True, verbose_name='日期')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Django_apps.students.FamilyInfo', verbose_name='家庭')),
            ],
        ),
        migrations.CreateModel(
            name='InheritedDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='遗传病')),
            ],
        ),
        migrations.CreateModel(
            name='StuClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='班级名称')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='学生名')),
                ('last_name', models.CharField(max_length=128, verbose_name='学生姓')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('nation', models.CharField(default='汉族', max_length=32, null=True, verbose_name='民族')),
                ('residence_province', models.CharField(max_length=16, null=True, verbose_name='户籍省')),
                ('residence_city', models.CharField(max_length=16, null=True, verbose_name='户籍市')),
                ('residence_region', models.CharField(max_length=16, null=True, verbose_name='户籍县区')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('day_age', models.IntegerField(verbose_name='日龄')),
                ('constellation', models.IntegerField(choices=[(1, '摩羯'), (2, '水瓶'), (3, '双鱼'), (4, '白羊'), (5, '金牛'), (6, '双子'), (7, '巨蟹'), (8, '狮子'), (9, '处女'), (10, '天秤'), (11, '天蝎'), (12, '射手')], verbose_name='星座')),
                ('chinese_zodiac', models.IntegerField(choices=[(1, '猴'), (2, '鸡'), (3, '狗'), (4, '猪'), (5, '鼠'), (6, '牛'), (7, '虎'), (8, '兔'), (9, '龙'), (10, '蛇'), (11, '马'), (12, '羊')], verbose_name='生肖')),
                ('photo', models.FileField(null=True, upload_to='student/photo/', verbose_name='照片')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='邮箱')),
                ('QQ', models.IntegerField(blank=True, null=True, unique=True, verbose_name='QQ')),
                ('wechat', models.CharField(blank=True, max_length=32, null=True, verbose_name='微信')),
                ('create_time', models.DateField(auto_now=True, verbose_name='创建日期')),
                ('period', models.IntegerField(verbose_name='届别')),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Django_apps.students.Country', verbose_name='国籍')),
                ('graduate_institutions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Django_apps.students.GraduateInstitutions', verbose_name='毕业园校')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='所在学校')),
                ('stu_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Django_apps.students.StuClass', verbose_name='所在班级')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInnerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interior_student_id', models.CharField(max_length=255, unique=True, verbose_name='内部学生ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Django_apps.students.StudentInfo')),
            ],
        ),
        migrations.CreateModel(
            name='StudentParents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='名')),
                ('last_name', models.CharField(max_length=64, verbose_name='姓')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('telephone', models.CharField(max_length=32, verbose_name='联系电话')),
                ('education', models.IntegerField(choices=[(0, '小学'), (1, '初中'), (2, '高中（中专'), (3, '大专'), (4, '本科'), (5, '硕士'), (6, '博士'), (7, '博士后'), (8, '院士')], verbose_name='学历')),
                ('company', models.CharField(max_length=64, verbose_name='工作单位')),
                ('job', models.CharField(max_length=32, verbose_name='职位')),
                ('wechat', models.CharField(max_length=32, null=True, verbose_name='微信')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPrivacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=256, verbose_name='学生全名')),
                ('id_card', models.CharField(db_index=True, max_length=32, null=True, unique=True, verbose_name='身份证号码')),
                ('student_code', models.IntegerField(null=True, verbose_name='学籍号')),
                ('telephone', models.CharField(max_length=32, null=True, verbose_name='电话号码')),
                ('student_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_privacy', to='Django_apps.students.StudentInfo', verbose_name='学生详细信息')),
            ],
        ),
        migrations.CreateModel(
            name='StudentToParents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.IntegerField(choices=[(1, '父亲'), (2, '母亲'), (3, '爷爷'), (4, '奶奶'), (5, '外公'), (6, '外婆')], verbose_name='与学生关系')),
                ('is_main_contact', models.BooleanField(verbose_name='是否为主要接送人')),
                ('parents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Django_apps.students.StudentParents', verbose_name='家长ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Django_apps.students.StudentPrivacy', verbose_name='学生ID')),
            ],
        ),
        migrations.CreateModel(
            name='WechatOpenID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=32, verbose_name='微信openID')),
            ],
        ),
        migrations.AddField(
            model_name='studentparents',
            name='wechat_open_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Django_apps.students.WechatOpenID', verbose_name='openID'),
        ),
        migrations.AddField(
            model_name='healthinfo',
            name='InheritedDisease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Django_apps.students.InheritedDisease', verbose_name='遗传病'),
        ),
        migrations.AddField(
            model_name='healthinfo',
            name='allergy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Django_apps.students.Allergy', verbose_name='过敏源'),
        ),
        migrations.AddField(
            model_name='healthinfo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Django_apps.students.StudentInfo'),
        ),
        migrations.AddField(
            model_name='familyinfo',
            name='family_status',
            field=models.ManyToManyField(to='Django_apps.students.FamilyStatus', verbose_name='家庭状况'),
        ),
        migrations.AddField(
            model_name='familyinfo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Django_apps.students.StudentPrivacy', verbose_name='学生'),
        ),
    ]
