# Generated by Django 2.1.1 on 2018-10-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='birthday',
            field=models.DateField(null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='chinese_zodiac',
            field=models.IntegerField(choices=[(1, '猴'), (2, '鸡'), (3, '狗'), (4, '猪'), (5, '鼠'), (6, '牛'), (7, '虎'), (8, '兔'), (9, '龙'), (10, '蛇'), (11, '马'), (12, '羊')], null=True, verbose_name='生肖'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='constellation',
            field=models.IntegerField(choices=[(1, '摩羯'), (2, '水瓶'), (3, '双鱼'), (4, '白羊'), (5, '金牛'), (6, '双子'), (7, '巨蟹'), (8, '狮子'), (9, '处女'), (10, '天秤'), (11, '天蝎'), (12, '射手')], null=True, verbose_name='星座'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='day_age',
            field=models.IntegerField(null=True, verbose_name='日龄'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='period',
            field=models.IntegerField(null=True, verbose_name='届别'),
        ),
    ]
