# Generated by Django 2.1.1 on 2018-10-12 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20181012_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='stu_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Django_apps.students.StuClass', verbose_name='所在班级'),
        ),
    ]
