# Generated by Django 2.1.1 on 2018-10-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20181015_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeaddress',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='homeaddress',
            name='city',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='市'),
        ),
        migrations.AlterField(
            model_name='homeaddress',
            name='province',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='省'),
        ),
        migrations.AlterField(
            model_name='homeaddress',
            name='region',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='区县'),
        ),
    ]
