# Generated by Django 2.1.1 on 2018-10-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20181015_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinfo',
            name='language',
            field=models.IntegerField(blank=True, choices=[(1, '中文普通话'), (2, '中文方言'), (3, '听力语言'), (4, '英语'), (5, '其他外语')], default=1, null=True, verbose_name='家庭语言'),
        ),
        migrations.AlterField(
            model_name='familyinfo',
            name='living_condition',
            field=models.IntegerField(blank=True, choices=[(1, '一居室'), (2, '二居室'), (3, '三居室'), (4, '三居以上')], null=True, verbose_name='居住条件'),
        ),
        migrations.AlterField(
            model_name='familyinfo',
            name='living_type',
            field=models.IntegerField(blank=True, choices=[(1, '一居室'), (2, '二居室'), (3, '三居室'), (4, '三居以上')], null=True, verbose_name='居住类型'),
        ),
    ]
