# Generated by Django 2.1.1 on 2018-10-16 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20181016_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttoparents',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='Django_apps.students.StudentPrivacy', verbose_name='学生ID'),
        ),
    ]
