# Generated by Django 2.1.1 on 2018-10-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20181016_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinfo',
            name='family_status',
            field=models.ManyToManyField(blank=True, null=True, to='Django_apps.students.FamilyStatus', verbose_name='家庭状况'),
        ),
    ]
