# Generated by Django 2.1.1 on 2018-10-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20181016_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentparents',
            name='education',
            field=models.IntegerField(blank=True, choices=[(1, '博士'), (2, '硕士'), (3, '本科'), (4, '大专'), (5, '高中'), (6, '高中以下')], null=True, verbose_name='学历'),
        ),
    ]
