# Generated by Django 2.1.1 on 2018-10-19 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20181019_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='interior_student_id',
        ),
    ]
