# Generated by Django 2.1.1 on 2018-10-19 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20181019_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinfo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Django_apps.students.StudentInfo', verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='studenttoparents',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='Django_apps.students.StudentInfo', verbose_name='学生ID'),
        ),
    ]
