# Generated by Django 2.1.1 on 2018-10-19 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_auto_20181018_0819'),
        ('students', '0019_auto_20181019_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='年级')),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='学校')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprivacy',
            name='student_detail',
        ),
        migrations.AddField(
            model_name='stuclass',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='学校'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='full_name',
            field=models.CharField(db_index=True, default=1, max_length=256, verbose_name='学生全名'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='id_card',
            field=models.CharField(db_index=True, max_length=32, null=True, verbose_name='身份证号码'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='student_code',
            field=models.IntegerField(null=True, verbose_name='学籍号'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='telephone',
            field=models.CharField(max_length=32, null=True, verbose_name='电话号码'),
        ),
        migrations.DeleteModel(
            name='StudentPrivacy',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Grade', verbose_name='年级'),
        ),
    ]
