# Generated by Django 2.1.1 on 2018-11-01 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_auto_20181101_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduateinstitutions',
            name='school_name',
        ),
        migrations.AddField(
            model_name='graduateinstitutions',
            name='name',
            field=models.CharField(default=1, max_length=32, verbose_name='学校名称'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='graduate_institutions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='school.SchoolInfo', verbose_name='毕业园校'),
        ),
    ]
