# Generated by Django 2.1.1 on 2018-11-06 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_auto_20181101_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scalevalue',
            name='scale_stu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scale_value', to='students.ScaleQuestion', verbose_name='对相应的学生量表'),
        ),
    ]
