# Generated by Django 2.1.1 on 2018-11-15 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0064_auto_20181114_0931'),
        ('students', '0031_auto_20181106_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.ChoiceTable', verbose_name='对应的选项表')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentInfo', verbose_name='对应学生')),
                ('values', models.ManyToManyField(to='school.ChoiceOptionsDes', verbose_name='对应选择的值')),
            ],
        ),
    ]
