# Generated by Django 2.1.1 on 2018-11-23 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_auto_20181122_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='stu_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='school.StuClass', verbose_name='所在班级'),
        ),
    ]
