# Generated by Django 2.1.1 on 2018-12-20 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0006_auto_20181220_0153'),
        ('students', '0036_auto_20181219_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttoparents',
            name='parents_wxinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weixinApp.WechatUserInfo', verbose_name='家长的微信信息'),
        ),
        migrations.AlterField(
            model_name='studenttoparents',
            name='is_main_contact',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否为主要接送人'),
        ),
    ]
