# Generated by Django 2.1.1 on 2019-01-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0038_auto_20181220_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, '男'), (2, '女')], default=None, null=True, verbose_name='性别'),
        ),
    ]
