# Generated by Django 2.1.1 on 2019-03-05 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0044_auto_20190305_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttoparents',
            name='parents_wxinfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_parent', to='weixinApp.WechatUserInfo', verbose_name='家长的微信信息'),
        ),
    ]
