# Generated by Django 2.1.1 on 2019-03-07 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0045_auto_20190305_0948'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='healthinfo',
            unique_together={('student', 'record_date')},
        ),
    ]
