# Generated by Django 2.1.1 on 2019-04-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0048_auto_20190409_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='身高'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='vision_left',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='左眼视力'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='vision_right',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='右眼视力'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='体重'),
        ),
    ]
