# Generated by Django 2.1.1 on 2019-04-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0050_auto_20190409_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='health_info',
        ),
    ]
