# Generated by Django 2.1.1 on 2019-04-09 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0052_healthrecord_health_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='health_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.HealthInfo', verbose_name='健康信息'),
        ),
    ]
