# Generated by Django 2.1.1 on 2019-04-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0055_auto_20190417_1639'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='familyinfo',
            unique_together={('student', 'create_time')},
        ),
        migrations.AlterModelTable(
            name='allergy',
            table='Allergy',
        ),
        migrations.AlterModelTable(
            name='choicequestion',
            table='ChoiceQuestion',
        ),
        migrations.AlterModelTable(
            name='country',
            table='Country',
        ),
        migrations.AlterModelTable(
            name='familyinfo',
            table='FamilyInfo',
        ),
        migrations.AlterModelTable(
            name='familymember',
            table='FamilyMember',
        ),
        migrations.AlterModelTable(
            name='familystatus',
            table='FamilyStatus',
        ),
        migrations.AlterModelTable(
            name='graduateinstitutions',
            table='GraduateInstitutions',
        ),
        migrations.AlterModelTable(
            name='healthinfo',
            table='HealthInfo',
        ),
        migrations.AlterModelTable(
            name='healthrecord',
            table='HealthRecord',
        ),
        migrations.AlterModelTable(
            name='homeaddress',
            table='HomeAddress',
        ),
        migrations.AlterModelTable(
            name='scalequestion',
            table='ScaleQuestion',
        ),
        migrations.AlterModelTable(
            name='scalevalue',
            table='ScaleValue',
        ),
        migrations.AlterModelTable(
            name='studentinfo',
            table='StudentInfo',
        ),
        migrations.AlterModelTable(
            name='studentparents',
            table='StudentParents',
        ),
        migrations.AlterModelTable(
            name='studenttoparents',
            table='StudentToParents',
        ),
    ]
