# Generated by Django 2.1.1 on 2019-05-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0058_studentparents_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentparents',
            name='gender',
        ),
    ]
