# Generated by Django 2.1.1 on 2019-05-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0059_remove_studentparents_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='student_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='学号'),
        ),
    ]
