# Generated by Django 2.1.1 on 2019-05-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0061_auto_20190517_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeaddress',
            name='create_time',
            field=models.DateField(auto_now=True, verbose_name='创建日期'),
        ),
        migrations.AlterUniqueTogether(
            name='familyinfo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='familyinfo',
            name='create_time',
        ),
    ]
