# Generated by Django 2.2.1 on 2019-06-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0062_auto_20190531_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '在校'), (2, '本校借读（学籍不在本校）'), (3, '保留学籍（学籍在本校）'), (4, '转学'), (5, '留级'), (6, '休学'), (7, '游学')], default=1, verbose_name='当前状态'),
        ),
    ]
