# Generated by Django 2.2.1 on 2019-06-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0063_studentinfo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentparents',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '在校'), (2, '本校借读'), (3, '保留学籍'), (4, '转学'), (5, '留级'), (6, '休学'), (7, '游学')], default=1, verbose_name='当前状态'),
        ),
    ]
