# Generated by Django 2.2.1 on 2019-06-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0064_auto_20190613_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentparents',
            old_name='phone',
            new_name='telephone',
        ),
    ]
