# Generated by Django 2.2.1 on 2019-07-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0098_auto_20190716_1217'),
        ('students', '0065_auto_20190613_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_1_dimension', models.SmallIntegerField(choices=[('start', '基本数据'), ('sport', '大运动'), ('language', '语言表达'), ('observe', '观察与评估记录')], verbose_name='一级维度')),
                ('level_2_dimension', models.SmallIntegerField(choices=[(1, '抛球'), (2, '单手丢沙包'), (3, '直线走'), (4, '单脚行进跳'), (5, '15米折返跑'), (6, '特殊问题'), (7, '')], verbose_name='二级维度')),
                ('boole_answer', models.BooleanField(blank=True, null=True, verbose_name='FT')),
                ('choice_question', models.SmallIntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], null=True, verbose_name='选择题答案')),
                ('score_answer', models.IntegerField(blank=True, null=True, verbose_name='分数答案')),
                ('number', models.SmallIntegerField(verbose_name='题目编号')),
            ],
            options={
                'db_table': 'Answers',
                'unique_together': {('level_1_dimension', 'number')},
            },
        ),
        migrations.CreateModel(
            name='QualityAssessmentSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_content', models.SmallIntegerField(blank=True, choices=[(1, '主观测'), (2, '客户观测'), (3, '精细动作'), (4, '大动作')], null=True, verbose_name='测试内容1')),
                ('dominant_hand', models.SmallIntegerField(blank=True, choices=[(1, '左手'), (2, '右手')], null=True, verbose_name='优势手')),
                ('test_time', models.DateTimeField(blank=True, null=True, verbose_name='测试时间')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='说明')),
                ('answers', models.ManyToManyField(to='students.Answers', verbose_name='答题情况')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='所在学校')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentInfo', unique=True, verbose_name='学生')),
            ],
            options={
                'db_table': 'QualityAssessmentSource',
            },
        ),
    ]
