# Generated by Django 2.2.1 on 2019-07-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0066_answers_qualityassessmentsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityassessmentsource',
            name='emotion',
            field=models.SmallIntegerField(blank=True, choices=[(1, '良好'), (2, '一般'), (3, '较差')], null=True, verbose_name='身体与情绪'),
        ),
    ]
