# Generated by Django 2.2.1 on 2019-07-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0067_qualityassessmentsource_emotion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qualityassessmentsource',
            unique_together={('student', 'test_time')},
        ),
    ]
