# Generated by Django 2.2.1 on 2019-07-16 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0069_auto_20190716_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityassessmentsource',
            name='answers',
        ),
        migrations.AddField(
            model_name='answers',
            name='assessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.QualityAssessmentSource', verbose_name='评测信息'),
            preserve_default=False,
        ),
    ]
