# Generated by Django 2.2.1 on 2019-07-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0070_auto_20190716_1727'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answers',
            unique_together={('level_1_dimension', 'number', 'assessment')},
        ),
    ]
