# Generated by Django 2.2.1 on 2019-07-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0071_auto_20190716_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='float_score',
            field=models.DecimalField(decimal_places=2, default=1.2, max_digits=3, verbose_name='浮点数记录'),
            preserve_default=False,
        ),
    ]
