# Generated by Django 2.2.1 on 2019-07-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0072_answers_float_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='float_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='浮点数记录'),
        ),
    ]
