# Generated by Django 2.2.1 on 2019-07-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0075_auto_20190717_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='excel_col_des',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Excel字段对应得描述'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='level_2_dimension',
            field=models.SmallIntegerField(blank=True, choices=[(1, '力量'), (2, '平衡'), (3, '速度'), (4, '特殊问题'), (5, '安全意识和自我保护'), (6, '安定情绪'), (7, '规则意识'), (8, '情绪识别'), (9, '群体生活'), (10, '适应能力'), (11, '倾听与表达')], null=True, verbose_name='二级维度'),
        ),
    ]
