# Generated by Django 2.2.1 on 2019-07-24 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0076_auto_20190717_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='choice_question',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], null=True, verbose_name='选择题答案'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='level_1_dimension',
            field=models.CharField(choices=[('base_info', '基本数据'), ('sport', '大运动'), ('language', '语言表达'), ('observe', '观察与评估记录'), ('action', '精细动作'), ('language_comprehension', '语言理解'), ('associate', '联想'), ('cognition_of_number', '数的认知'), ('logic', '逻辑'), ('attention', '持续注意'), ('short_memory', '短时记忆'), ('science', '科学常识'), ('life', '生活常识'), ('habits_of_life', '生活习惯和卫生习惯'), ('safety_consciousness', '安全意识'), ('society', '社会'), ('art', '艺术素养'), ('interest', '兴趣爱好')], max_length=64, verbose_name='一级维度'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='level_2_dimension',
            field=models.SmallIntegerField(blank=True, choices=[(1, '力量'), (2, '平衡'), (3, '速度'), (4, '特殊问题'), (5, '安全意识和自我保护'), (6, '安定情绪'), (7, '规则意识'), (8, '情绪识别'), (9, '群体生活'), (10, '适应能力'), (11, '倾听与表达'), (12, '手眼协调'), (13, '动作灵活'), (14, '表现与创造'), (15, '动作灵活和表现与创造'), (16, '自理能力'), (17, '安全意识和自我保护'), (18, '群体生活'), (19, '规则意识'), (20, '自主表现'), (21, '尊重他人'), (22, '感受与欣赏'), (23, '表现与创造'), (24, '美术与书法'), (25, '音乐'), (26, '体育'), (27, '高科技产品'), (28, '逻辑思维'), (29, '科学探究'), (30, '社会'), (31, '法律与金融'), (32, '法律'), (33, '购物'), (34, '音乐'), (35, '编程'), (36, '戏曲')], null=True, verbose_name='二级维度'),
        ),
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_dimension', models.SmallIntegerField(choices=[(1, '科学'), (2, '语言'), (3, '社会'), (4, '健康'), (5, '艺术'), (6, '兴趣爱好'), (7, '其他')], verbose_name='一级维度')),
                ('level_2_dimension', models.SmallIntegerField(choices=[(1, '大运动'), (2, '联想'), (3, '数的认知'), (4, '逻辑思维'), (5, '持续思维'), (6, '短时记忆'), (7, '科学常识'), (8, '生活常识'), (9, '语言理解'), (10, '语言表达'), (11, '群体生活'), (12, '规则意识'), (13, '尊重他人'), (14, '自主表现'), (15, '情绪识别'), (16, '生活习惯与卫生习惯'), (17, '安全意识和自我保护'), (18, '自理能力'), (19, '精细动作'), (20, '感受与欣赏'), (21, '表现与创造'), (22, '兴趣爱好'), (23, '美术与书法'), (24, '音乐'), (25, '体育'), (26, '高科技产品'), (27, '逻辑思维'), (28, '科学探究'), (29, '社会'), (30, '法律与金融')], verbose_name='二级维度')),
                ('score', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='浮点数记录')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.QualityAssessmentSource', verbose_name='评测信息')),
            ],
            options={
                'db_table': 'AssessmentScore',
                'unique_together': {('top_dimension', 'level_2_dimension', 'assessment', 'score')},
            },
        ),
    ]
