# Generated by Django 2.2.1 on 2019-07-24 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0077_auto_20190724_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinfo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentInfo'),
        ),
    ]
