# Generated by Django 2.2.1 on 2019-07-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0078_auto_20190724_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentscore',
            name='level_2_dimension',
            field=models.SmallIntegerField(choices=[(1, '大运动'), (2, '联想'), (3, '数的认知'), (4, '逻辑思维'), (5, '持续注意'), (6, '短时记忆'), (7, '科学常识'), (8, '生活常识'), (9, '语言理解'), (10, '语言表达'), (11, '群体生活'), (12, '规则意识'), (13, '尊重他人'), (14, '自主表现'), (15, '情绪识别'), (16, '生活习惯与卫生习惯'), (17, '安全意识和自我保护'), (18, '自理能力'), (19, '精细动作'), (20, '感受与欣赏'), (21, '表现与创造'), (22, '兴趣爱好'), (23, '美术与书法'), (24, '音乐'), (25, '体育'), (26, '高科技产品'), (27, '逻辑思维'), (28, '科学探究'), (29, '社会'), (30, '法律与金融')], verbose_name='二级维度'),
        ),
        migrations.AlterField(
            model_name='assessmentscore',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='浮点数记录'),
        ),
    ]
