# Generated by Django 2.2.1 on 2019-10-09 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0098_auto_20190716_1217'),
        ('students', '0080_auto_20190801_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='level_2_dimension',
            field=models.SmallIntegerField(blank=True, choices=[(1, '力量'), (2, '平衡'), (3, '速度'), (4, '特殊问题'), (5, '安全意识和自我保护'), (6, '安定情绪'), (7, '规则意识'), (8, '情绪识别'), (9, '群体生活'), (10, '适应能力'), (11, '倾听与表达'), (12, '手眼协调'), (13, '动作灵活'), (14, '表现与创造'), (15, '动作灵活和表现与创造'), (16, '自理能力'), (17, '安全意识和自我保护'), (18, '群体生活'), (19, '规则意识'), (20, '自主表现'), (21, '尊重他人'), (22, '感受与欣赏'), (23, '表现与创造'), (24, '美术与书法'), (25, '音乐'), (26, '体育'), (27, '高科技产品'), (28, '逻辑思维'), (29, '科学探究'), (30, '社会'), (31, '法律与金融')], null=True, verbose_name='二级维度'),
        ),
        migrations.CreateModel(
            name='GraduatedStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='毕业学校')),
            ],
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='graduate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.GraduatedStudent', verbose_name='毕业情况'),
        ),
    ]
