# Generated by Django 2.2.1 on 2019-10-09 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0081_auto_20191009_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='graduate',
        ),
        migrations.AddField(
            model_name='graduatedstudent',
            name='graduate',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.GraduatedStudent', verbose_name='毕业生信息'),
            preserve_default=False,
        ),
    ]
