# Generated by Django 2.2.1 on 2019-10-09 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0082_auto_20191009_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduatedstudent',
            name='graduate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.StudentInfo', verbose_name='毕业生信息'),
        ),
    ]
