# Generated by Django 2.2.1 on 2019-10-09 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0083_auto_20191009_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduatedstudent',
            name='graduate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduate_student', to='students.StudentInfo', verbose_name='毕业生信息'),
        ),
    ]
