# Generated by Django 2.2.1 on 2019-10-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0084_auto_20191009_1103'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='graduatedstudent',
            table='GraduatedStudent',
        ),
    ]
