# Generated by Django 2.2.1 on 2019-11-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0085_auto_20191012_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentparents',
            name='full_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='姓名'),
        ),
    ]
