# Generated by Django 2.1.1 on 2018-12-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0073_schooltimetable_info_type'),
        ('weixinApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wechatbindinfo',
            old_name='school_id',
            new_name='school',
        ),
        migrations.AlterUniqueTogether(
            name='wechatbindinfo',
            unique_together={('school', 'open_id')},
        ),
    ]
