# Generated by Django 2.1.1 on 2018-12-19 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0002_auto_20181218_0934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='wechatuserinfo',
            name='status',
        ),
        migrations.AddField(
            model_name='wechatbindinfo',
            name='salt',
            field=models.CharField(default=1, max_length=32, verbose_name='用于加密'),
        ),
        migrations.AddField(
            model_name='wechatbindinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '正常'), (2, '异常')], default=1, verbose_name='账号状态'),
        ),
        migrations.AddField(
            model_name='wechatuserinfo',
            name='bind_info',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='weixinApp.WechatBindInfo', verbose_name='绑定openid的信息'),
        ),
    ]
