# Generated by Django 2.1.1 on 2018-12-19 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0003_auto_20181219_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatbindinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '正常'), (2, '异常')], verbose_name='账号状态'),
        ),
        migrations.AlterField(
            model_name='wechatuserinfo',
            name='bind_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weixinApp.WechatBindInfo', verbose_name='绑定openid的信息'),
        ),
    ]
