# Generated by Django 2.1.1 on 2018-12-20 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0005_auto_20181219_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatuserinfo',
            name='bind_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wx_user', to='weixinApp.WechatBindInfo', verbose_name='绑定openid的信息'),
        ),
        migrations.AlterField(
            model_name='wechatuserinfo',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
