# Generated by Django 2.1.1 on 2019-02-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0007_familyvisitrecord'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wechatbindinfo',
            table='WechatBindInfo',
        ),
        migrations.AlterModelTable(
            name='wechatuserinfo',
            table='WechatUserInfo',
        ),
    ]
