# Generated by Django 2.1.1 on 2019-02-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0008_auto_20190218_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyvisitrecord',
            name='create_time',
            field=models.DateField(auto_created=True, default=1, verbose_name='创建时间'),
        ),
    ]
