# Generated by Django 2.1.1 on 2019-02-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0019_auto_20190220_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyvisitrecord',
            name='visit_date',
            field=models.DateTimeField(verbose_name='访问时间'),
        ),
    ]
