# Generated by Django 2.1.1 on 2019-02-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0021_auto_20190220_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyvisitrecord',
            name='create_time',
            field=models.DateField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='wechatbindinfo',
            name='bind_time',
            field=models.DateField(auto_now=True, verbose_name='绑定小程序的事件'),
        ),
    ]
