# Generated by Django 2.1.1 on 2019-02-25 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('weixinApp', '0022_auto_20190221_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='时间')),
                ('object_id', models.PositiveIntegerField()),
                ('event', models.PositiveSmallIntegerField(choices=[(1, '家访'), (2, '预约')], verbose_name='事件类型')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='familyvisitrecord',
            name='visit_time',
        ),
    ]
