# Generated by Django 2.1.1 on 2019-02-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0023_auto_20190225_0746'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schedule',
            table='Schedule',
        ),
    ]
