# Generated by Django 2.1.1 on 2019-02-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0025_auto_20190226_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(verbose_name='日期时间'),
        ),
    ]
