# Generated by Django 2.1.1 on 2019-02-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0029_auto_20190228_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexnotification',
            name='associated_users',
        ),
        migrations.RemoveField(
            model_name='indexnotification',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='IndexNotification',
        ),
    ]
