# Generated by Django 2.1.1 on 2019-02-28 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('weixinApp', '0030_auto_20190228_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('event', models.PositiveSmallIntegerField(choices=[(1, '家访'), (2, '徽章'), (3, '报表'), (4, '作业')], verbose_name='事件类型')),
                ('object_id', models.PositiveIntegerField()),
                ('associated_users', models.ManyToManyField(to='weixinApp.WechatUserInfo', verbose_name='关联的用户')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'IndexNotification',
            },
        ),
    ]
