# Generated by Django 2.1.1 on 2019-03-04 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0043_auto_20190228_0803'),
        ('school', '0081_auto_20190214_0706'),
        ('weixinApp', '0032_indexnotification_is_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emblem_name', models.CharField(max_length=64, verbose_name='徽章名称')),
                ('custom_name', models.CharField(max_length=64, verbose_name='自定义名称')),
                ('icon', models.FileField(upload_to='emblem/icon', verbose_name='徽章图标')),
                ('photo', models.FileField(blank=True, null=True, upload_to='emblem/photo', verbose_name='自定制图片')),
                ('description', models.TextField(max_length=128, verbose_name='徽章描述')),
                ('is_custom', models.BooleanField(default=False, verbose_name='是否允许自定制')),
                ('classification', models.SmallIntegerField(choices=[(1, '鼓励与表扬'), (2, '惩罚与批评')], verbose_name='徽章分类选择')),
                ('scope', models.SmallIntegerField(blank=True, choices=[(1, '校级'), (2, '班级')], null=True, verbose_name='颁发范围')),
                ('emblem_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixinApp.Emblem', verbose_name='徽章类型')),
                ('grade', models.ManyToManyField(to='school.Grade', verbose_name='适用年级')),
                ('school', models.ForeignKey(blank=True, help_text='如果允许自定制，关联学校的ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='学校')),
                ('subject', models.ManyToManyField(to='school.Course', verbose_name='学科维度')),
            ],
            options={
                'db_table': 'Emblem',
            },
        ),
        migrations.CreateModel(
            name='EmblemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=64, verbose_name='标题描述')),
                ('sub_type', models.ForeignKey(blank=True, help_text='如果不为空代表是一个描述子类', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='weixinApp.EmblemType', verbose_name='二级分类')),
            ],
            options={
                'db_table': 'EmblemType',
            },
        ),
        migrations.CreateModel(
            name='IssuedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='颁发日期')),
                ('time', models.TimeField(auto_now=True, verbose_name='颁发时间')),
                ('comment', models.TextField(max_length=128, verbose_name='评语')),
                ('emblem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixinApp.Emblem', verbose_name='徽章')),
                ('issuing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixinApp.WechatUserInfo', verbose_name='颁发人')),
                ('student', models.ManyToManyField(to='students.StudentInfo', verbose_name='对应学生')),
            ],
            options={
                'db_table': 'IssuedRecord',
            },
        ),
        migrations.AlterUniqueTogether(
            name='emblem',
            unique_together={('emblem_name', 'emblem_type')},
        ),
    ]
