# Generated by Django 2.1.1 on 2019-03-04 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0036_auto_20190304_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emblemtype',
            name='sub_type',
        ),
        migrations.AddField(
            model_name='emblemtype',
            name='pid',
            field=models.ForeignKey(blank=True, help_text='如果不为空代表是一个描述子类', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='weixinApp.EmblemType', verbose_name='父级分类'),
        ),
        migrations.AlterField(
            model_name='emblem',
            name='grade',
            field=models.ManyToManyField(blank=True, null=True, to='school.Grade', verbose_name='适用年级'),
        ),
        migrations.AlterField(
            model_name='emblem',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, to='school.Course', verbose_name='学科维度'),
        ),
    ]
