# Generated by Django 2.1.1 on 2019-03-20 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0038_auto_20190305_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emblem',
            name='school',
            field=models.ForeignKey(blank=True, default=None, help_text='如果允许自定制，关联学校的ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='emblem',
            name='scope',
            field=models.SmallIntegerField(blank=True, choices=[(1, '校级'), (2, '班级')], default=None, null=True, verbose_name='颁发范围'),
        ),
        migrations.AlterField(
            model_name='familyvisitrecord',
            name='relate_parents',
            field=models.ManyToManyField(to='weixinApp.WechatUserInfo', verbose_name='关联家长的微信信息'),
        ),
    ]
