# Generated by Django 2.1.1 on 2018-10-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20181012_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprivacy',
            name='id_card',
            field=models.CharField(db_index=True, max_length=32, null=True, verbose_name='身份证号码'),
        ),
    ]
