# Generated by Django 2.1.1 on 2018-10-19 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_auto_20181019_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='stuclass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='full_name',
            field=models.CharField(db_index=True, max_length=256, verbose_name='学生全名'),
        ),
    ]
