# Generated by Django 2.1.1 on 2018-10-29 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_auto_20181019_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='images',
            new_name='img',
        ),
    ]
