# Generated by Django 2.1.1 on 2018-10-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_scalequestion_scalevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='interior_student_id',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='内部学生ID'),
        ),
        migrations.AlterField(
            model_name='studentparents',
            name='education',
            field=models.IntegerField(blank=True, choices=[(1, '博士'), (2, '硕士'), (3, '本科'), (4, '大专'), (5, '高中'), (6, '高中以下'), (7, '暂不知道')], null=True, verbose_name='学历'),
        ),
    ]
