# Generated by Django 2.1.1 on 2018-11-01 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_auto_20181101_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduateinstitutions',
            name='school_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='学校名称'),
        ),
    ]
