# Generated by Django 2.1.1 on 2018-11-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_auto_20181101_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduateinstitutions',
            name='name',
            field=models.CharField(max_length=32, verbose_name='学校名称'),
        ),
    ]
