# Generated by Django 2.1.1 on 2019-04-09 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0047_studentparents_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(null=True, verbose_name='身高')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='体重')),
                ('vision_left', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='左眼视力')),
                ('vision_right', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='右眼视力')),
                ('vision_status', models.IntegerField(null=True, verbose_name='视力情况')),
                ('record_date', models.DateField(auto_now=True, verbose_name='记录日期')),
                ('measure_type', models.ImageField(blank=True, choices=[(1, '校测'), (2, '自测')], default=1, null=True, upload_to='', verbose_name='测试类型')),
            ],
        ),
        migrations.AlterField(
            model_name='healthinfo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentInfo', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='healthinfo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='health_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.HealthInfo', verbose_name='健康信息'),
        ),
        migrations.RemoveField(
            model_name='healthinfo',
            name='height',
        ),
        migrations.RemoveField(
            model_name='healthinfo',
            name='record_date',
        ),
        migrations.RemoveField(
            model_name='healthinfo',
            name='vision_left',
        ),
        migrations.RemoveField(
            model_name='healthinfo',
            name='vision_right',
        ),
        migrations.RemoveField(
            model_name='healthinfo',
            name='vision_status',
        ),
        migrations.RemoveField(
            model_name='healthinfo',
            name='weight',
        ),
    ]
