# Generated by Django 2.1.1 on 2019-05-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0056_auto_20190429_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentparents',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='生日'),
        ),
    ]
