# Generated by Django 2.1.1 on 2019-05-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0095_auto_20190513_1132'),
        ('students', '0060_studentinfo_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='student_code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='学籍号'),
        ),
        migrations.AlterUniqueTogether(
            name='studentinfo',
            unique_together={('full_name', 'student_id', 'grade')},
        ),
    ]
