# Generated by Django 2.1.1 on 2018-10-11 06:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20181011_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='internal_id',
            field=models.CharField(default=uuid.UUID('5bd81ef3-e587-4db9-8375-8f8d35b107a6'), max_length=255, unique=True, verbose_name='学校内部ID'),
        ),
    ]
