# Generated by Django 2.1.1 on 2018-10-11 06:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20181011_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='internal_id',
            field=models.CharField(default=uuid.UUID('f71b1597-f5b3-419d-a0f5-0bd0949c4508'), max_length=255, unique=True, verbose_name='学校内部ID'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='Qrcode',
            field=models.CharField(max_length=255, null=True, verbose_name='二维码'),
        ),
    ]
