# Generated by Django 2.1.1 on 2018-10-11 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20181011_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='internal_id',
            field=models.CharField(default=uuid.UUID('0d543da8-2000-408f-bda7-a86e7311d7ba'), max_length=255, unique=True, verbose_name='学校内部ID'),
        ),
    ]
