# Generated by Django 2.1.1 on 2018-10-11 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20181011_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='internal_id',
            field=models.CharField(default=uuid.UUID('b0de57c0-86ef-4fc1-850b-56934fabed61'), max_length=255, unique=True, verbose_name='学校内部ID'),
        ),
    ]
