# Generated by Django 2.1.1 on 2018-10-11 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20181011_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='internal_id',
            field=models.CharField(default=uuid.UUID('ae51bd2d-ebc0-47ed-acdf-30c6cdd2275f'), max_length=255, unique=True, verbose_name='学校内部ID'),
        ),
    ]
