# Generated by Django 2.1.1 on 2018-10-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_schoolinfo_internal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='internal_id',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='学校内部ID'),
        ),
    ]
