# Generated by Django 2.1.1 on 2018-10-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20181011_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='internal_id',
            field=models.CharField(default=1, max_length=255, verbose_name='学校内部ID'),
        ),
    ]
