# Generated by Django 2.1.1 on 2018-10-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20181011_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolinfo',
            name='internal_id',
        ),
    ]
