# Generated by Django 2.1.1 on 2018-10-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_auto_20181017_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='internal_id',
            field=models.CharField(max_length=255, verbose_name='学校内部ID'),
        ),
    ]
