# Generated by Django 2.1.1 on 2018-10-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0041_auto_20181019_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='title',
            new_name='grade_name',
        ),
    ]
