# Generated by Django 2.1.1 on 2018-10-19 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0042_auto_20181019_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuclass',
            name='grade',
        ),
    ]
