# Generated by Django 2.1.1 on 2018-10-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0044_stuclass_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuclass',
            name='grade',
        ),
    ]
