# Generated by Django 2.1.1 on 2018-10-19 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0047_auto_20181019_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolinfo',
            name='class_set',
        ),
        migrations.AddField(
            model_name='stuclass',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='学校'),
        ),
        migrations.RemoveField(
            model_name='stuclass',
            name='grade',
        ),
        migrations.AddField(
            model_name='stuclass',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.Grade', verbose_name='年级'),
        ),
    ]
