# Generated by Django 2.1.1 on 2018-10-29 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0051_auto_20181029_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scalelinetitle',
            name='scale_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.ScaleSetting', verbose_name='对应的量表'),
        ),
        migrations.AlterField(
            model_name='scaleoptiondes',
            name='scale_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.ScaleSetting', verbose_name='对应的量表'),
        ),
    ]
