# Generated by Django 2.1.1 on 2018-10-31 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0058_auto_20181030_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableinfo',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_info', to='school.TableSettings', verbose_name='对应的表单'),
        ),
    ]
