# Generated by Django 2.1.1 on 2018-11-13 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0061_auto_20181101_0746'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stuclass',
            unique_together={('grade', 'school', 'name')},
        ),
    ]
