# Generated by Django 2.1.1 on 2018-11-14 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0063_auto_20181114_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceoptionsdes',
            name='choice_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opdes', to='school.ChoiceTable', verbose_name='对应的选择表'),
        ),
    ]
