# Generated by Django 2.1.1 on 2018-11-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0064_auto_20181114_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceoptionsdes',
            name='des',
            field=models.CharField(max_length=64, verbose_name='每个选项的描述'),
        ),
        migrations.AlterField(
            model_name='scalelinetitle',
            name='des',
            field=models.CharField(max_length=64, verbose_name='量表行标题'),
        ),
    ]
