# Generated by Django 2.1.1 on 2018-11-16 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0065_auto_20181116_0222'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='settingtofield',
            unique_together={('setting', 'fields')},
        ),
    ]
