# Generated by Django 2.1.1 on 2018-12-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0067_schoolcalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolcalendar',
            name='date_des',
            field=models.IntegerField(choices=[(1, '开学'), (2, '寒假'), (4, '暑假'), (3, '校动会'), (5, '期中考试'), (6, '期末考试'), (7, '校庆'), (8, '毕业典礼')], default=1, verbose_name='日期描述'),
        ),
        migrations.AddField(
            model_name='schoolcalendar',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
    ]
