# Generated by Django 2.1.1 on 2018-12-04 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_auto_20181127_0726'),
        ('school', '0069_auto_20181203_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_des', models.CharField(max_length=32, verbose_name='课程名称')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.SmallIntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五')], verbose_name='星期')),
                ('time_range', models.SmallIntegerField(choices=[(1, '7:00 - 8:00'), (2, '8:00 - 9:00'), (3, '9:00 - 10:00')], verbose_name='时间段')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Course', verbose_name='课程')),
                ('stu_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.StuClass', verbose_name='班级')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherInfo', verbose_name='代课老师')),
            ],
        ),
    ]
