# Generated by Django 2.1.1 on 2018-12-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0073_schooltimetable_info_type'),
        ('school', '0062_auto_20181113_0232'),
    ]

    operations = [
    ]
