# Generated by Django 2.1.1 on 2019-01-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0078_auto_20190118_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='period',
            field=models.SmallIntegerField(verbose_name='学段'),
        ),
    ]
