# Generated by Django 2.1.1 on 2019-02-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0080_auto_20190128_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='period',
            field=models.SmallIntegerField(choices=[(1, '小学'), (2, '中学'), (3, '小学中学')], verbose_name='学段'),
        ),
    ]
