# Generated by Django 2.1.1 on 2019-04-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0082_remove_schooltimetable_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopeoffilling',
            name='name',
            field=models.IntegerField(choices=[(1, '家长'), (2, '老师'), (3, '学生')], verbose_name='填表范围'),
        ),
    ]
