# Generated by Django 2.1.1 on 2019-04-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0084_auto_20190419_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='scalesetting',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='表单描述'),
        ),
        migrations.AddField(
            model_name='scalesetting',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已发布'), (2, '未发布')], default=1, verbose_name='状态'),
        ),
    ]
