# Generated by Django 2.1.1 on 2019-05-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0090_tablesettings_peroration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableinfo',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
