# Generated by Django 2.1.1 on 2019-05-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0093_auto_20190509_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormLoginFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=128, verbose_name='字段名称')),
            ],
        ),
        migrations.AddField(
            model_name='tablesettings',
            name='login_fields',
            field=models.ManyToManyField(to='school.FormLoginFields', verbose_name='登陆字段'),
        ),
    ]
