# Generated by Django 2.1.1 on 2019-05-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0094_auto_20190513_1130'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='formloginfields',
            table='FormLoginFields',
        ),
    ]
