# Generated by Django 2.1.1 on 2018-10-11 06:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='机构名称')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldName', models.CharField(max_length=32, verbose_name='字段名称')),
                ('field_english', models.CharField(max_length=32, verbose_name='字段英文名')),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='居委会')),
            ],
        ),
        migrations.CreateModel(
            name='CompetentOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='主管部门')),
            ],
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, '学生信息'), (2, '健康信息'), (3, '家庭信息'), (4, '家长信息')], verbose_name='所属分类')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='集团名称')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='专业名称')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolBoundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], verbose_name='年度')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(1, '改名'), (2, '搬迁'), (3, '拆分'), (4, '合并')], verbose_name='记录类型')),
                ('start_time', models.DateField(verbose_name='开始日期')),
                ('end_time', models.DateField(verbose_name='结束日期')),
                ('old_name', models.CharField(max_length=64, verbose_name='学校源名称')),
                ('new_name', models.CharField(max_length=64, verbose_name='学校新名称')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolHonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='荣誉名称')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Assessment', verbose_name='评测机构')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(db_index=True, max_length=64, verbose_name='学校名称')),
                ('English_name', models.CharField(max_length=64, null=True, verbose_name='学校英文名称')),
                ('abbreviation', models.CharField(max_length=16, null=True, verbose_name='学校简称')),
                ('internal_id', models.CharField(default=uuid.UUID('95c02c79-2e05-4746-bf12-7d8bcdf5f5a6'), max_length=255, unique=True, verbose_name='学校内部ID')),
                ('school_code', models.CharField(max_length=64, null=True, verbose_name='学校编码')),
                ('country', models.CharField(default='中国', max_length=32, verbose_name='国家')),
                ('local_school_name', models.CharField(max_length=64, null=True, verbose_name='学校本地名')),
                ('logo', models.FileField(null=True, upload_to='school/logo/', verbose_name='学校LOGO')),
                ('pattern', models.FileField(null=True, upload_to='school/pattern/', verbose_name='学校图案')),
                ('website', models.URLField(max_length=128, null=True, verbose_name='学校官网')),
                ('school_type', models.IntegerField(choices=[(1, '公立'), (2, '民办')], verbose_name='学校类型')),
                ('school_layer', models.IntegerField(choices=[(1, '幼儿园'), (2, '小学'), (3, '中学'), (4, '九年一贯制')], verbose_name='学校层级')),
                ('create_time', models.DateField(null=True, verbose_name='创办时间')),
                ('province', models.CharField(max_length=32, verbose_name='所在省')),
                ('city', models.CharField(max_length=32, verbose_name='所在市')),
                ('region', models.CharField(max_length=32, verbose_name='所在区县')),
                ('street', models.CharField(max_length=32, null=True, verbose_name='所在街道办,乡镇')),
                ('address', models.CharField(max_length=128, verbose_name='校址')),
                ('campus_district', models.CharField(blank=True, max_length=32, null=True, verbose_name='校区名称')),
                ('campus_english_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='校区英文名')),
                ('community', models.ForeignKey(null=True, on_delete=models.Model, to='school.Community', verbose_name='所在居委会')),
                ('competent_organization', models.ManyToManyField(to='school.CompetentOrganization', verbose_name='主管单位')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Group', verbose_name='教育集团')),
                ('major', models.ManyToManyField(to='school.Major', verbose_name='开设课程')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_time', models.DateField(verbose_name='开始日期')),
                ('end_time', models.DateField(verbose_name='结束日期')),
                ('title', models.CharField(max_length=64, verbose_name='名称')),
                ('Qrcode', models.CharField(default=None, max_length=255, verbose_name='二维码')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='称号名称')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolToHonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(verbose_name='获取时间')),
                ('honor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolHonor', verbose_name='荣誉')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='学校')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolToTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(verbose_name='获取时间')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='学校')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolTitle', verbose_name='称号')),
            ],
        ),
        migrations.CreateModel(
            name='ScopeOfFilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, '老师'), (2, '家长'), (3, '学生')], verbose_name='填表范围')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField(verbose_name='分数线')),
                ('Year', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], verbose_name='年度')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='学校')),
            ],
        ),
        migrations.CreateModel(
            name='SettingToField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='排序')),
                ('fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.ChoiceField', verbose_name='字段')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolSettings', verbose_name='设置信息')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='系统名称')),
            ],
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='fill_range',
            field=models.ManyToManyField(to='school.ScopeOfFilling', verbose_name='填表范围'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='school_range',
            field=models.ManyToManyField(related_name='setting', to='school.SchoolInfo', verbose_name='学校范围'),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.System', verbose_name='办学系统'),
        ),
        migrations.AddField(
            model_name='schoolhistory',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='学校'),
        ),
        migrations.AddField(
            model_name='schoolboundary',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='学校'),
        ),
        migrations.AddField(
            model_name='choicefield',
            name='field_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.FieldType', verbose_name='类型'),
        ),
    ]
