# Generated by Django 2.1.1 on 2018-10-11 06:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='internal_id',
            field=models.CharField(default=uuid.UUID('d49cc54e-36bf-4138-afd9-0c547f04a696'), max_length=255, unique=True, verbose_name='学校内部ID'),
        ),
    ]
