# Generated by Django 2.1.1 on 2018-10-11 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20181011_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='internal_id',
            field=models.CharField(default=uuid.UUID('e6097ef3-9a97-4093-85ae-a01b1c14e178'), max_length=255, unique=True, verbose_name='学校内部ID'),
        ),
    ]
