# Generated by Django 2.1.1 on 2018-10-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_remove_schoolinfo_internal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='internal_id',
            field=models.CharField(default=1, max_length=255, verbose_name='学校内部ID'),
        ),
    ]
