# Generated by Django 2.1.1 on 2018-10-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_schoolinfo_internal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='is_main_campus',
            field=models.BooleanField(default=True, verbose_name='是否是本部'),
        ),
    ]
