# Generated by Django 2.1.1 on 2018-10-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_auto_20181017_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='school_type',
            field=models.IntegerField(choices=[(1, '公立'), (2, '民办')], default=1, verbose_name='学校类型'),
        ),
    ]
