# Generated by Django 2.1.1 on 2018-10-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_auto_20181018_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='internal_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='学校内部ID'),
        ),
    ]
