# Generated by Django 2.1.1 on 2018-10-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_auto_20181018_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='school_type',
            field=models.CharField(blank=True, choices=[('1', '公立'), ('2', '民办')], default=None, max_length=4, null=True, verbose_name='学校类型'),
        ),
    ]
