# Generated by Django 2.1.1 on 2018-10-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_auto_20181018_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='logo',
            field=models.FileField(default='school/logo/default.png', null=True, upload_to='school/logo/', verbose_name='学校LOGO'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='pattern',
            field=models.FileField(default='school/logo/default.png', null=True, upload_to='school/pattern/', verbose_name='学校图案'),
        ),
    ]
