# Generated by Django 2.1.1 on 2018-10-19 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_auto_20181018_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='年级')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='学校')),
            ],
        ),
        migrations.CreateModel(
            name='StuClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='班级名称')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='学校')),
            ],
        ),
    ]
