# Generated by Django 2.1.1 on 2018-10-19 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0037_grade_stuclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuclass',
            name='school',
        ),
        migrations.AddField(
            model_name='stuclass',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.Grade', verbose_name='年级'),
        ),
    ]
