# Generated by Django 2.1.1 on 2018-10-19 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0038_auto_20181019_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuclass',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Grade', verbose_name='年级'),
        ),
    ]
