# Generated by Django 2.1.1 on 2018-10-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0039_auto_20181019_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='school',
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='class_set',
            field=models.ManyToManyField(to='school.StuClass', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='title',
            field=models.IntegerField(choices=[(1, '一年级'), (2, '二年级'), (3, '三年级'), (4, '四年级'), (5, '五年级'), (6, '六年级'), (7, '初一'), (8, '初二')], verbose_name='年级'),
        ),
        migrations.RemoveField(
            model_name='stuclass',
            name='grade',
        ),
        migrations.AddField(
            model_name='stuclass',
            name='grade',
            field=models.ManyToManyField(to='school.Grade', verbose_name='年级'),
        ),
    ]
