# Generated by Django 2.1.1 on 2018-10-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0045_remove_stuclass_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuclass',
            name='grade',
            field=models.ManyToManyField(to='school.Grade', verbose_name='年级'),
        ),
    ]
