# Generated by Django 2.1.1 on 2018-10-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0046_stuclass_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuclass',
            name='grade',
            field=models.ManyToManyField(default=1, to='school.Grade', verbose_name='年级'),
        ),
    ]
