# Generated by Django 2.1.1 on 2018-10-29 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0050_auto_20181029_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scalesetting',
            name='line_title',
        ),
        migrations.RemoveField(
            model_name='scalesetting',
            name='option_des',
        ),
        migrations.AddField(
            model_name='scalelinetitle',
            name='scale_table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.ScaleSetting', verbose_name='对应的量表'),
        ),
        migrations.AddField(
            model_name='scaleoptiondes',
            name='scale_table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.ScaleSetting', verbose_name='对应的量表'),
        ),
    ]
