# Generated by Django 2.1.1 on 2018-10-29 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0054_auto_20181029_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scalelinetitle',
            name='scale_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_title', to='school.ScaleSetting', verbose_name='对应的量表'),
        ),
        migrations.AlterField(
            model_name='scaleoptiondes',
            name='scale_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='school.ScaleSetting', verbose_name='对应的量表'),
        ),
    ]
