# Generated by Django 2.1.1 on 2018-10-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0055_auto_20181029_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='SchoolSettings',
            new_name='TableSettings',
        ),
    ]
