# Generated by Django 2.1.1 on 2018-10-30 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0057_auto_20181030_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableinfo',
            name='finish_time',
            field=models.IntegerField(verbose_name='填表完成的时间(以秒为单位)'),
        ),
        migrations.AlterField(
            model_name='tableinfo',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.TableSettings', verbose_name='对应的表单'),
        ),
    ]
