# Generated by Django 2.1.1 on 2018-11-14 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0061_auto_20181101_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceOptionsDes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=32, verbose_name='每个选项的描述')),
                ('choice_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.ChoiceField', verbose_name='对应的选择表')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('choice_type', models.PositiveIntegerField(choices=[(1, '单选'), (2, '多选')], verbose_name='单选或多选')),
                ('setting_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='school.TableSettings', verbose_name='对应的表单')),
            ],
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_name',
            field=models.IntegerField(choices=[(1, '一年级'), (2, '二年级'), (3, '三年级'), (4, '四年级'), (5, '五年级'), (6, '六年级'), (7, '初一'), (8, '初二'), (9, '初三'), (10, '高一'), (11, '高二'), (12, '高三'), (13, '小班'), (14, '中班'), (15, '大班')], unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='stuclass',
            unique_together={('grade', 'school', 'name')},
        ),
    ]
