# Generated by Django 2.1.1 on 2018-12-06 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0071_auto_20181206_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooltimetable',
            name='other_event',
            field=models.SmallIntegerField(blank=True, choices=[(1, '课间操'), (2, '午休')], null=True, verbose_name='学校其他事件'),
        ),
        migrations.AlterField(
            model_name='schooltimetable',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='schooltimetable',
            name='single_double_week',
            field=models.SmallIntegerField(blank=True, choices=[(1, '单'), (2, '双')], null=True, verbose_name='课程单双周'),
        ),
    ]
