# Generated by Django 2.1.1 on 2019-01-09 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0074_schooltimetable_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='WXappSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_img', models.ImageField(upload_to='school/wx/background/')),
                ('status', models.SmallIntegerField(choices=[(1, '正常'), (2, '关闭')], default=1, verbose_name='小程序状态')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='所对应的学校')),
            ],
        ),
        migrations.AlterField(
            model_name='schoolboundary',
            name='Year',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], verbose_name='年度'),
        ),
        migrations.AlterField(
            model_name='scoreline',
            name='Year',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], verbose_name='年度'),
        ),
        migrations.AlterField(
            model_name='tableinfo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_student', to='students.StudentInfo', verbose_name='填表的学生'),
        ),
    ]
