# Generated by Django 2.1.1 on 2019-01-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0076_auto_20190109_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxappsettings',
            name='background_img',
            field=models.FileField(upload_to='school/wx/background/'),
        ),
    ]
