# Generated by Django 2.1.1 on 2019-01-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0077_auto_20190109_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='简称'),
        ),
        migrations.AddField(
            model_name='course',
            name='period',
            field=models.SmallIntegerField(default=1, verbose_name='学段'),
        ),
        migrations.AlterField(
            model_name='schooltimetable',
            name='other_event',
            field=models.SmallIntegerField(blank=True, choices=[(1, '课间操'), (2, '午休'), (3, '早读'), (4, '课外活动'), (5, '眼保健操'), (6, '大课间')], null=True, verbose_name='学校其他事件'),
        ),
        migrations.AlterField(
            model_name='schooltimetable',
            name='single_double_week',
            field=models.SmallIntegerField(blank=True, choices=[(1, '每周'), (2, '单周'), (3, '双周')], null=True, verbose_name='课程单双周'),
        ),
    ]
