# Generated by Django 2.1.1 on 2019-04-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0085_auto_20190423_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scalesetting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='scalesetting',
            name='status',
        ),
        migrations.AddField(
            model_name='tablesettings',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='表单描述'),
        ),
        migrations.AddField(
            model_name='tablesettings',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已发布'), (2, '未发布')], default=1, verbose_name='状态'),
        ),
    ]
