# Generated by Django 2.1.1 on 2019-04-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0087_auto_20190423_1354'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assessment',
            table='Assessment',
        ),
        migrations.AlterModelTable(
            name='community',
            table='Community',
        ),
        migrations.AlterModelTable(
            name='competentorganization',
            table='CompetentOrganization',
        ),
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
        migrations.AlterModelTable(
            name='group',
            table='Group',
        ),
        migrations.AlterModelTable(
            name='major',
            table='Major',
        ),
        migrations.AlterModelTable(
            name='schoolboundary',
            table='SchoolBoundary',
        ),
        migrations.AlterModelTable(
            name='schoolcalendar',
            table='SchoolCalendar',
        ),
        migrations.AlterModelTable(
            name='schoolhistory',
            table='SchoolHistory',
        ),
        migrations.AlterModelTable(
            name='schoolhonor',
            table='SchoolHonor',
        ),
        migrations.AlterModelTable(
            name='schooltimerange',
            table='SchoolTimeRange',
        ),
        migrations.AlterModelTable(
            name='schooltimetable',
            table='SchoolTimetable',
        ),
        migrations.AlterModelTable(
            name='schooltitle',
            table='SchoolTitle',
        ),
        migrations.AlterModelTable(
            name='schooltohonor',
            table='SchoolToHonor',
        ),
        migrations.AlterModelTable(
            name='schooltotitle',
            table='SchoolToTitle',
        ),
        migrations.AlterModelTable(
            name='scoreline',
            table='ScoreLine',
        ),
        migrations.AlterModelTable(
            name='system',
            table='System',
        ),
    ]
