# Generated by Django 2.1.1 on 2019-05-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0089_auto_20190423_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesettings',
            name='peroration',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='结束语'),
        ),
    ]
