# Generated by Django 2.2.1 on 2019-07-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0096_auto_20190529_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesettings',
            name='Repeatable',
            field=models.BooleanField(blank=True, default=False, verbose_name='是否能重复填写'),
        ),
        migrations.AlterField(
            model_name='tablesettings',
            name='end_time',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='tablesettings',
            name='stat_time',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='tablesettings',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='名称'),
        ),
    ]
