# Generated by Django 2.2.1 on 2019-07-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0097_auto_20190715_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='校址'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='city',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='所在市'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='province',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='所在省'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='region',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='所在区县'),
        ),
    ]
