# Generated by Django 2.2.1 on 2019-10-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0098_auto_20190716_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=512, verbose_name='题干')),
                ('question_type', models.SmallIntegerField(choices=[(1, '单选'), (2, '多选'), (3, '判断'), (4, '填空')], verbose_name='题型')),
                ('crate_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(null=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'QuestionBank',
            },
        ),
    ]
