# Generated by Django 2.2.1 on 2019-10-23 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190218_0701'),
        ('school', '0099_questionbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='crate_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo', verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionbank',
            name='relate_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.Course', verbose_name='关联课程'),
            preserve_default=False,
        ),
    ]
