# Generated by Django 2.2.1 on 2019-11-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0100_auto_20191023_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='school_type',
            field=models.CharField(blank=True, choices=[('1', '公立'), ('2', '民办'), ('3', '培训机构')], default=None, max_length=4, null=True, verbose_name='学校类型'),
        ),
    ]
