# Generated by Django 2.1.1 on 2018-12-18 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0073_schooltimetable_info_type'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateField(blank=True, null=True, verbose_name='更新时间')),
                ('create_time', models.DateField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='WechatBindInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=128, verbose_name='openid')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolInfo', verbose_name='学校ID')),
            ],
        ),
        migrations.CreateModel(
            name='WechatUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(db_index=True, max_length=64, verbose_name='微信昵称')),
                ('avatar', models.URLField(max_length=128, verbose_name='头像')),
                ('status', models.SmallIntegerField(choices=[(1, '正常'), (2, '异常')], verbose_name='账号状态')),
                ('updated_time', models.DateField(blank=True, null=True, verbose_name='更新时间')),
                ('create_time', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('user_type', models.SmallIntegerField(choices=[(1, '家长'), (2, '老师'), (3, '学生')], verbose_name='用户类型')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='wechatbindinfo',
            unique_together={('school_id', 'open_id')},
        ),
    ]
