# Generated by Django 2.1.1 on 2019-02-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0012_auto_20190218_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyvisitrecord',
            name='create_time',
        ),
    ]
