# Generated by Django 2.1.1 on 2019-02-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0015_auto_20190218_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatbindinfo',
            name='bind_time',
            field=models.DateField(auto_created=True, default='2019-2-18', verbose_name='绑定小程序的事件'),
        ),
    ]
