# Generated by Django 2.1.1 on 2019-02-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0016_wechatbindinfo_bind_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatbindinfo',
            name='bind_time',
            field=models.DateField(auto_created=True, verbose_name='绑定小程序的事件'),
        ),
    ]
