# Generated by Django 2.1.1 on 2019-02-20 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0028_auto_20190219_0649'),
        ('weixinApp', '0017_auto_20190218_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyvisitrecord',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherInfo', verbose_name='访问的老师'),
        ),
    ]
