# Generated by Django 2.1.1 on 2019-02-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0027_indexnotification'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='indexnotification',
            table='IndexNotificatio',
        ),
    ]
