# Generated by Django 2.1.1 on 2019-03-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0033_auto_20190304_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='emblem',
            name='issuer',
            field=models.SmallIntegerField(choices=[(1, '老师'), (2, '家长'), (3, '两者皆可')], default=1, verbose_name='颁发者分类'),
        ),
    ]
