# Generated by Django 2.1.1 on 2019-03-05 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0037_auto_20190304_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emblemtype',
            old_name='tittle',
            new_name='title',
        ),
    ]
