# Generated by Django 2.2.1 on 2019-11-08 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0101_auto_20191106_1555'),
        ('weixinApp', '0039_auto_20190320_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowseOfNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_time', models.DateTimeField(auto_now=True, verbose_name='查看时间')),
            ],
        ),
        migrations.AlterField(
            model_name='indexnotification',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(1, '家访'), (2, '徽章'), (3, '报表'), (4, '作业'), (5, '通知')], verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='wechatuserinfo',
            name='user_type',
            field=models.SmallIntegerField(choices=[(1, '家长'), (2, '老师'), (3, '学生')], null=True, verbose_name='用户类型'),
        ),
        migrations.CreateModel(
            name='SchoolNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='名称')),
                ('content', models.CharField(max_length=255, verbose_name='内容描述')),
                ('note_type', models.SmallIntegerField(choices=[(1, '每日学科'), (2, '重要通知'), (3, '情况说明')])),
                ('photo', models.FileField(blank=True, null=True, upload_to='school/notify/', verbose_name='照片')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('associate_class', models.ManyToManyField(to='school.StuClass', verbose_name='关联班级')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify', to='weixinApp.WechatUserInfo', verbose_name='发布人')),
            ],
        ),
    ]
