# Generated by Django 2.2.1 on 2019-11-14 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0040_auto_20191108_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='browseofnotification',
            name='read_notify',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weixinApp.SchoolNotification', verbose_name='阅读消息'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='browseofnotification',
            name='read_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weixinApp.WechatUserInfo', verbose_name='阅读用户'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='schoolnotification',
            unique_together={('create_user', 'title', 'content')},
        ),
        migrations.AlterModelTable(
            name='schoolnotification',
            table='SchoolNotification',
        ),
    ]
