# Generated by Django 2.2.1 on 2019-11-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0041_auto_20191114_0957'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='browseofnotification',
            unique_together={('read_time', 'read_notify', 'read_user')},
        ),
        migrations.AlterModelTable(
            name='browseofnotification',
            table='BrowseOfNotification',
        ),
    ]
