# Generated by Django 2.2.1 on 2019-11-14 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0086_studentparents_full_name'),
        ('weixinApp', '0042_auto_20191114_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskForLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.PositiveSmallIntegerField(choices=[(1, '事假'), (2, '病假'), (3, '其他原因')], verbose_name='请假事由')),
                ('begin_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixinApp.WechatUserInfo', verbose_name='申请人')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentInfo', verbose_name='请求学生')),
            ],
            options={
                'db_table': 'AskForLeave',
                'unique_together': {('begin_time', 'end_time', 'student')},
            },
        ),
    ]
