# Generated by Django 2.2.1 on 2019-11-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixinApp', '0043_askforleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='askforleave',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建日期'),
        ),
    ]
