# Generated by Django 2.1.1 on 2019-02-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_familyvisitrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyvisitrecord',
            name='relate_parents',
        ),
        migrations.RemoveField(
            model_name='familyvisitrecord',
            name='student',
        ),
        migrations.DeleteModel(
            name='FamilyVisitRecord',
        ),
    ]
