# Generated by Django 2.1.1 on 2018-11-08 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20181106_0304'),
        ('students', '0031_auto_20181106_0322'),
        ('StudentMentalHealth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentInfo', verbose_name='对应学生')),
                ('teacher', models.ForeignKey(limit_choices_to={'id__in': [2]}, on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherInfo', verbose_name='对应的心理老师')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='日期')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentInfo', verbose_name='对应学生')),
                ('teacher', models.ForeignKey(limit_choices_to={'id__in': [2]}, on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherInfo', verbose_name='对应的心理老师')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(choices=[(1, 'AM9:00'), (2, 'AM10:00'), (3, 'AM11:00'), (4, 'PM2:30'), (5, 'PM3:30'), (6, 'PM4:30')])),
            ],
        ),
        migrations.CreateModel(
            name='TeacherEditTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(limit_choices_to={'id__in': [2]}, on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherInfo', verbose_name='对应的心理老师')),
            ],
        ),
        migrations.AddField(
            model_name='individualstudentrecord',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherInfo', verbose_name='记录的老师'),
        ),
        migrations.AddField(
            model_name='appointmentmanage',
            name='tine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentMentalHealth.AvailableTime', verbose_name='对应时段'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('student', 'teacher', 'time')},
        ),
    ]
