# Generated by Django 2.1.1 on 2018-11-09 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentMentalHealth', '0004_auto_20181109_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentmanage',
            old_name='data',
            new_name='date',
        ),
    ]
