# Generated by Django 2.1.1 on 2018-11-06 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0030_auto_20181101_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualStudentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateField(auto_now=True, verbose_name='记录时间')),
                ('scale_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.ScaleQuestion', verbose_name='对相应的学生量表')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentInfo', verbose_name='对应学生')),
            ],
        ),
    ]
