# Generated by Django 2.1.1 on 2018-11-08 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentMentalHealth', '0002_auto_20181108_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualstudentrecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherInfo', verbose_name='记录的老师'),
        ),
    ]
