# Generated by Django 2.1.1 on 2018-11-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentMentalHealth', '0003_auto_20181108_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentmanage',
            old_name='tine',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='time',
            field=models.IntegerField(choices=[(1, 'AM 9:00 - AM 10:00'), (2, 'PM15:30 - PM16:30')]),
        ),
    ]
