# Generated by Django 2.1.1 on 2018-11-22 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentMentalHealth', '0005_auto_20181109_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmanage',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_appointment', to='students.StudentInfo', verbose_name='对应学生'),
        ),
    ]
