# Generated by Django 2.2.1 on 2019-10-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentMentalHealth', '0008_auto_20191012_1049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
