# Generated by Django 2.2.1 on 2019-10-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentMentalHealth', '0010_performance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
