# Generated by Django 2.2.1 on 2019-10-12 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0085_auto_20191012_1042'),
        ('StudentMentalHealth', '0011_delete_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.SmallIntegerField(choices=[(1, '与年龄明显不符的集中困难'), (2, '不能遵守课堂与学校的规则，如擅自离座、走动'), (3, '行为冲动，如爱插嘴、攻击他人'), (4, '尖叫'), (5, '情绪失控'), (6, '与人缺乏眼神交流'), (7, '动作刻板，环境刻板'), (8, '攻击他人'), (9, '敌意'), (10, '愤怒情绪'), (11, '拒绝身体接触'), (12, '手脚配合笨拙，易跌倒'), (13, '东西整理乱'), (14, '阅读时必须手指指读读，容易漏字、漏行'), (15, 'b/d,p/q,w/m这类字母无法区分'), (16, '手指精细动作有困难')], verbose_name='选项')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_performance', to='students.StudentInfo', verbose_name='对应学生')),
            ],
        ),
    ]
