# Generated by Django 2.1.1 on 2018-11-05 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20181102_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtoteacher',
            name='stu_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handle_class', to='school.StuClass', verbose_name='班级'),
        ),
    ]
