# Generated by Django 2.1.1 on 2018-11-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20181106_0304'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherinfo',
            unique_together={('first_name', 'last_name', 'birthday', 'telephone')},
        ),
    ]
