# Generated by Django 2.1.1 on 2018-11-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20181123_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtoteacher',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
