# Generated by Django 2.1.1 on 2019-01-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_remove_teacherinfo_wechat_open_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtoteacher',
            name='relate',
            field=models.SmallIntegerField(choices=[(1, '班主任'), (2, '代课老师')], default=1, verbose_name='教师与班级的对应关系'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='telephone',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='wechat',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='微信'),
        ),
    ]
