# Generated by Django 2.1.1 on 2019-01-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_auto_20190116_1012'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherinfo',
            unique_together={('first_name', 'last_name', 'birthday', 'telephone', 'wechat')},
        ),
    ]
