# Generated by Django 2.1.1 on 2019-02-19 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0027_auto_20190218_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtoteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='teacher.TeacherInfo', verbose_name='老师'),
        ),
    ]
